name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup PHP environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # PHP 8.3
          extensions: json, curl
          tools: composer

      # Install dependencies
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

        # Copy .env file
      - name: Copy .env file
        run: cp .github/workflows/.env.github .env

      # PHP Unit tests
      - name: Run PHPUnit
        run: vendor/bin/phpunit

      # PHPStan analysis
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

      # PHP CodeSniffer checks
      - name: Run PHP CodeSniffer
        run: vendor/bin/phpcs

      - name: Run Rector
        run: vendor/bin/rector process --dry-run
